# master branch
# compile, test, release to nuget
-
  branches:
    only:
    - master

  version: 0.3.0.{build}

  init:
  - ps: |
      $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
      $env:AssemblyVersion = $Version.ToString()
      $env:PackageVersion = "{0}.{1}.{2}" -f $version.Major, $version.Minor, $version.Build

  before_build:
  - dotnet restore

  build_script:
  - ps: dotnet build -c Release /p:AssemblyVersion=$($env:AssemblyVersion) /p:ProductVersion=$($env:AssemblyVersion)

  after_build:
  - ps: dotnet pack .\Odin\Odin.csproj /p:PackageVersion="$($env:PackageVersion)" -o .

  artifacts:
  - path: 'Odin-Commands*.nupkg'
    name: odin-nuget-package

  deploy:
  - provider: NuGet
    api_key:
      secure: rjdM45vvxrIcK6Jk66jXXSZTSVI7LfxoV9PoXDyGQvk9hZsDSuRSuiDxu7G45k3A
    artifact: odin-nuget-package

  notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/3712526962bd70e49d63
    on_build_failure: true
    on_build_success: true
    on_build_status_changed: true

# release branches
# compile, test, release beta version to nuget
-
  version: 0.3.0.{build}

  branches:
    only:
    - /release\/.*/

  init:
  - ps: |
      $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
      $env:AssemblyVersion = $Version.ToString()
      $env:PackageVersion = "{0}.{1}.{2}-beta-{3}" -f $version.Major, $version.Minor, $version.Build, $version.Revision

  before_build:
  - dotnet restore

  build_script:
  - ps: dotnet build -c Release /p:AssemblyVersion=$($env:AssemblyVersion) /p:ProductVersion=$($env:AssemblyVersion)

  after_build:
  - ps: dotnet pack .\Odin\Odin.csproj /p:PackageVersion="$env:PackageVersion" -o .

  artifacts:
  - path: 'Odin-Commands*.nupkg'
    name: odin-nuget-package

  deploy:
  - provider: NuGet
    api_key:
      secure: rjdM45vvxrIcK6Jk66jXXSZTSVI7LfxoV9PoXDyGQvk9hZsDSuRSuiDxu7G45k3A
    artifact: odin-nuget-package

  notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/3712526962bd70e49d63
    on_build_failure: true
    on_build_success: true
    on_build_status_changed: true

# all other branches
# compile, test
-
  version: 0.3.0.{build}

  before_build:
  - dotnet restore

  build_script:
  - ps: dotnet build -c Release

  notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/3712526962bd70e49d63
    on_build_failure: true
    on_build_success: true
    on_build_status_changed: true
