# master branch
# compile, test, release to nuget
-
  branches:
    only:
    - master

  version: 0.2.0.{build}
  environment:
    packageVersion: 0.2.0

  init:
  - ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
  - ps: $env:nugetVersion = $env:packageVersion
  - ps: Update-AppveyorBuild -Version $env:buildVersion

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(buildVersion)'
    assembly_file_version: '$(buildVersion)'
    assembly_informational_version: '$(nugetVersion)'

  configuration: Release

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true

  before_build:
  - nuget restore

  build:
    verbosity: minimal

  after_build:
  - ps: nuget pack Odin-Commands.nuspec -version "$env:nugetVersion"

  artifacts:
  - path: 'Odin-Commands*.nupkg'
    name: odin-nuget-package

  deploy:
  - provider: NuGet
    api_key:
      secure: oZLUyd94wnic5VlRfHZnlopK4I2tNOT30JMOp0nWrH/i+ZOyVYKayPbfy407OZdL
    artifact: odin-nuget-package

  notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/3712526962bd70e49d63
    on_build_failure: true
    on_build_success: true
    on_build_status_changed: true

# release branches
# compile, test, release beta version to nuget
-
  version: 0.2.0.{build}
  environment:
    packageVersion: 0.2.0

  branches:
    only:
    - /release\/.*/

  init:
  - ps: $env:buildVersion = "{0}.{1}" -f $env:packageVersion, $env:appveyor_build_number
  - ps: $env:nugetVersion = "{0}-beta-{1}" -f $env:packageVersion, $env:appveyor_build_number
  - ps: write-host "Release branch build version   -  $env:buildVersion"
  - ps: write-host "Release branch package version -  $env:nugetVersion"
  - ps: Update-AppveyorBuild -Version $env:buildVersion

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(buildVersion)'
    assembly_file_version: '$(buildVersion)'
    assembly_informational_version: '$(nugetVersion)'

  configuration: Release

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true

  before_build:
  - nuget restore

  build:
    verbosity: minimal

  after_build:
  - ps: nuget pack Odin-Commands.nuspec -version "$env:nugetVersion"

  artifacts:
  - path: 'Odin-Commands*.nupkg'
    name: odin-nuget-package

  deploy:
  - provider: NuGet
    api_key:
      secure: oZLUyd94wnic5VlRfHZnlopK4I2tNOT30JMOp0nWrH/i+ZOyVYKayPbfy407OZdL
    artifact: odin-nuget-package

  notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/3712526962bd70e49d63
    on_build_failure: true
    on_build_success: true
    on_build_status_changed: true

# all other branches
# compile, test
-
  version: 0.2.0.{build}
  environment:
    packageVersion: 0.2.0

  init:
  - ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
  - ps: Update-AppveyorBuild -Version $env:buildVersion

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(buildVersion)'
    assembly_file_version: '$(buildVersion)'
    assembly_informational_version: '$(nugetVersion)'

  configuration: Release

  before_build:
  - nuget restore

  build:
    verbosity: minimal
    
  notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/3712526962bd70e49d63
    on_build_failure: true
    on_build_success: true
    on_build_status_changed: true
