# master branch
# compile, test, release to nuget
-
  branches:
    only:
    - master

  version: 1.0.0.{build}

  init:
  - ps: |
      $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
      $env:PackageVersion = "{0}.{1}.{2}" -f $version.Major, $version.Minor, $version.Build

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_informational_version: '$(APPVEYOR_BUILD_VERSION)'

  configuration: Release

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true

  before_build:
  - dotnet restore

  build_script:
  - ps: dotnet build

  build:
    verbosity: minimal

  after_build:
  - ps: dotnet pack .\Odin\Odin.csproj /p:PackageVersion="$env:PackageVersion"

  artifacts:
  - path: 'Odin-Commands*.nupkg'
    name: odin-nuget-package

  deploy:
  - provider: NuGet
    api_key:
      secure: oZLUyd94wnic5VlRfHZnlopK4I2tNOT30JMOp0nWrH/i+ZOyVYKayPbfy407OZdL
    artifact: odin-nuget-package

  notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/3712526962bd70e49d63
    on_build_failure: true
    on_build_success: true
    on_build_status_changed: true

# release branches
# compile, test, release beta version to nuget
-
  version: 1.0.0.{build}

  branches:
    only:
    - /release\/.*/

  init:
  - ps: |
      $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
      $env:PackageVersion = "{0}.{1}.{2}-beta-{3}" -f $version.Major, $version.Minor, $version.Build, $version.Revision

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_informational_version: '$(PackageVersion)'

  configuration: Release

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true

  before_build:
  - dotnet restore

  build_script:
  - ps: dotnet build
  
  build:
    verbosity: minimal

  after_build:
  - ps: dotnet pack .\Odin\Odin.csproj /p:PackageVersion="$env:PackageVersion"

  artifacts:
  - path: 'Odin-Commands*.nupkg'
    name: odin-nuget-package

  deploy:
  - provider: NuGet
    api_key:
      secure: oZLUyd94wnic5VlRfHZnlopK4I2tNOT30JMOp0nWrH/i+ZOyVYKayPbfy407OZdL
    artifact: odin-nuget-package

  notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/3712526962bd70e49d63
    on_build_failure: true
    on_build_success: true
    on_build_status_changed: true

# all other branches
# compile, test
-
  version: 0.2.3.{build}

  configuration: Release

  before_build:
  - dotnet restore

  build_script:
    - ps: dotnet build

  build:
    verbosity: minimal

  notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/3712526962bd70e49d63
    on_build_failure: true
    on_build_success: true
    on_build_status_changed: true
